version: "3"

services:
  server:
    container_name: "test-server"
    build: .
    volumes:
      - ./app/data:/home/data
    ports:
      - "8000:8000"
    command: python manage.py runserver --nostatic 0.0.0.0:8000
  poll_outgoing_transactions:
    container_name: "test-poll_outgoing_transactions"
    build: .
    volumes:
      - ./app/data:/home/data
    command: python manage.py poll_outgoing_transactions --loop
  execute_outgoing_transactions:
    container_name: "test-execute_outgoing_transactions"
    build: .
    volumes:
      - ./app/data:/home/data
    command: python manage.py execute_outgoing_transactions --loop
  watch_transaction:
    container_name: "test-watch_transactions"
    build: .
    volumes:
      - ./app/data:/home/data
    command: python manage.py watch_transactions
  poll_pending_deposits:
    container_name: "test-poll_pending_deposits"
    build: .
    volumes:
      - ./app/data:/home/data
    command: python manage.py poll_pending_deposits --loop
